### ISSUE TITLE
[mclxIOstreamIn] no assignments yield void/empty matrix

### ISSUE THREAD

**Issue by hcli007** [Gabaldonlab/EvolClust#1]
Hi Marina，
I try to run some of my own data with EvolCluster， everything was ok when I use testdataset：
`python evolclust.py -i test_dataset.mcl -f test_dataset.fa -d evol_test --local`

but when I use my own data ，Some errors occurred， It seems to be about mcl：
nohup: ignoring input
STEP1: Create initial files
STEP2: Calculate thresholds and obtain pairwise clusters (This can take a long time)
Processed:  0 out of 27912
Processed:  1000 out of 27912
Processed:  2000 out of 27912
Processed:  3000 out of 27912
Processed:  4000 out of 27912
Processed:  5000 out of 27912
Processed:  6000 out of 27912
Processed:  7000 out of 27912
Processed:  8000 out of 27912
Processed:  9000 out of 27912
Processed:  10000 out of 27912
Processed:  11000 out of 27912
Processed:  12000 out of 27912
Processed:  13000 out of 27912
Processed:  14000 out of 27912
Processed:  15000 out of 27912
Processed:  16000 out of 27912
Processed:  17000 out of 27912
Processed:  18000 out of 27912
Processed:  19000 out of 27912
Processed:  20000 out of 27912
Processed:  21000 out of 27912
Processed:  22000 out of 27912
Processed:  23000 out of 27912
Processed:  24000 out of 27912
Processed:  25000 out of 27912
Processed:  26000 out of 27912
Processed:  27000 out of 27912
Processed:  0 out of 60757
Processed:  1000 out of 60757
Processed:  2000 out of 60757
Processed:  3000 out of 60757
Processed:  4000 out of 60757
Processed:  5000 out of 60757
Processed:  6000 out of 60757
Processed:  7000 out of 60757
Processed:  8000 out of 60757
Processed:  9000 out of 60757
Processed:  10000 out of 60757
Processed:  11000 out of 60757
Processed:  12000 out of 60757
Processed:  13000 out of 60757
Processed:  14000 out of 60757
Processed:  15000 out of 60757
Processed:  16000 out of 60757
Processed:  17000 out of 60757
Processed:  18000 out of 60757
Processed:  19000 out of 60757
Processed:  20000 out of 60757
Processed:  21000 out of 60757
Processed:  22000 out of 60757
Processed:  23000 out of 60757
Processed:  24000 out of 60757
Processed:  25000 out of 60757
Processed:  26000 out of 60757
Processed:  27000 out of 60757
Processed:  28000 out of 60757
Processed:  29000 out of 60757
Processed:  30000 out of 60757
Processed:  31000 out of 60757
Processed:  32000 out of 60757
Processed:  33000 out of 60757
Processed:  34000 out of 60757
Processed:  35000 out of 60757
Processed:  36000 out of 60757
Processed:  37000 out of 60757
Processed:  38000 out of 60757
Processed:  39000 out of 60757
Processed:  40000 out of 60757
Processed:  41000 out of 60757
Processed:  42000 out of 60757
Processed:  43000 out of 60757
Processed:  44000 out of 60757
Processed:  45000 out of 60757
Processed:  46000 out of 60757
Processed:  47000 out of 60757
Processed:  48000 out of 60757
Processed:  49000 out of 60757
Processed:  50000 out of 60757
Processed:  51000 out of 60757
Processed:  52000 out of 60757
Processed:  53000 out of 60757
Processed:  54000 out of 60757
Processed:  55000 out of 60757
Processed:  56000 out of 60757
Processed:  57000 out of 60757
Processed:  58000 out of 60757
Processed:  59000 out of 60757
Processed:  60000 out of 60757
Processed:  0 out of 35165
Processed:  1000 out of 35165
Processed:  2000 out of 35165
Processed:  3000 out of 35165
Processed:  4000 out of 35165
Processed:  5000 out of 35165
Processed:  6000 out of 35165
Processed:  7000 out of 35165
Processed:  8000 out of 35165
Processed:  9000 out of 35165
Processed:  10000 out of 35165
Processed:  11000 out of 35165
Processed:  12000 out of 35165
Processed:  13000 out of 35165
Processed:  14000 out of 35165
Processed:  15000 out of 35165
Processed:  16000 out of 35165
Processed:  17000 out of 35165
Processed:  18000 out of 35165
Processed:  19000 out of 35165
Processed:  20000 out of 35165
Processed:  21000 out of 35165
Processed:  22000 out of 35165
Processed:  23000 out of 35165
Processed:  24000 out of 35165
Processed:  25000 out of 35165
Processed:  26000 out of 35165
Processed:  27000 out of 35165
Processed:  28000 out of 35165
Processed:  29000 out of 35165
Processed:  30000 out of 35165
Processed:  31000 out of 35165
Processed:  32000 out of 35165
Processed:  33000 out of 35165
Processed:  34000 out of 35165
Processed:  35000 out of 35165
Processed:  0 out of 53705
Processed:  1000 out of 53705
Processed:  2000 out of 53705
Processed:  3000 out of 53705
Processed:  4000 out of 53705
Processed:  5000 out of 53705
Processed:  6000 out of 53705
Processed:  7000 out of 53705
Processed:  8000 out of 53705
Processed:  9000 out of 53705
Processed:  10000 out of 53705
Processed:  11000 out of 53705
Processed:  12000 out of 53705
Processed:  13000 out of 53705
Processed:  14000 out of 53705
Processed:  15000 out of 53705
Processed:  16000 out of 53705
Processed:  17000 out of 53705
Processed:  18000 out of 53705
Processed:  19000 out of 53705
Processed:  20000 out of 53705
Processed:  21000 out of 53705
Processed:  22000 out of 53705
Processed:  23000 out of 53705
Processed:  24000 out of 53705
Processed:  25000 out of 53705
Processed:  26000 out of 53705
Processed:  27000 out of 53705
Processed:  28000 out of 53705
Processed:  29000 out of 53705
Processed:  30000 out of 53705
Processed:  31000 out of 53705
Processed:  32000 out of 53705
Processed:  33000 out of 53705
Processed:  34000 out of 53705
Processed:  35000 out of 53705
Processed:  36000 out of 53705
Processed:  37000 out of 53705
Processed:  38000 out of 53705
Processed:  39000 out of 53705
Processed:  40000 out of 53705
Processed:  41000 out of 53705
Processed:  42000 out of 53705
Processed:  43000 out of 53705
Processed:  44000 out of 53705
Processed:  45000 out of 53705
Processed:  46000 out of 53705
Processed:  47000 out of 53705
Processed:  48000 out of 53705
Processed:  49000 out of 53705
Processed:  50000 out of 53705
Processed:  51000 out of 53705
Processed:  52000 out of 53705
Processed:  53000 out of 53705
Processed:  0 out of 33505
Processed:  1000 out of 33505
Processed:  2000 out of 33505
Processed:  3000 out of 33505
Processed:  4000 out of 33505
Processed:  5000 out of 33505
Processed:  6000 out of 33505
Processed:  7000 out of 33505
Processed:  8000 out of 33505
Processed:  9000 out of 33505
Processed:  10000 out of 33505
Processed:  11000 out of 33505
Processed:  12000 out of 33505
Processed:  13000 out of 33505
Processed:  14000 out of 33505
Processed:  15000 out of 33505
Processed:  16000 out of 33505
Processed:  17000 out of 33505
Processed:  18000 out of 33505
Processed:  19000 out of 33505
Processed:  20000 out of 33505
Processed:  21000 out of 33505
Processed:  22000 out of 33505
Processed:  23000 out of 33505
Processed:  24000 out of 33505
Processed:  25000 out of 33505
Processed:  26000 out of 33505
Processed:  27000 out of 33505
Processed:  28000 out of 33505
Processed:  29000 out of 33505
Processed:  30000 out of 33505
Processed:  31000 out of 33505
Processed:  32000 out of 33505
Processed:  33000 out of 33505
Processed:  0 out of 68289
Processed:  1000 out of 68289
Processed:  2000 out of 68289
Processed:  3000 out of 68289
Processed:  4000 out of 68289
Processed:  5000 out of 68289
Processed:  6000 out of 68289
Processed:  7000 out of 68289
Processed:  8000 out of 68289
Processed:  9000 out of 68289
Processed:  10000 out of 68289
Processed:  11000 out of 68289
Processed:  12000 out of 68289
Processed:  13000 out of 68289
Processed:  14000 out of 68289
Processed:  15000 out of 68289
Processed:  16000 out of 68289
Processed:  17000 out of 68289
Processed:  18000 out of 68289
Processed:  19000 out of 68289
Processed:  20000 out of 68289
Processed:  21000 out of 68289
Processed:  22000 out of 68289
Processed:  23000 out of 68289
Processed:  24000 out of 68289
Processed:  25000 out of 68289
Processed:  26000 out of 68289
Processed:  27000 out of 68289
Processed:  28000 out of 68289
Processed:  29000 out of 68289
Processed:  30000 out of 68289
Processed:  31000 out of 68289
Processed:  32000 out of 68289
Processed:  33000 out of 68289
Processed:  34000 out of 68289
Processed:  35000 out of 68289
Processed:  36000 out of 68289
Processed:  37000 out of 68289
Processed:  38000 out of 68289
Processed:  39000 out of 68289
Processed:  40000 out of 68289
Processed:  41000 out of 68289
Processed:  42000 out of 68289
Processed:  43000 out of 68289
Processed:  44000 out of 68289
Processed:  45000 out of 68289
Processed:  46000 out of 68289
Processed:  47000 out of 68289
Processed:  48000 out of 68289
Processed:  49000 out of 68289
Processed:  50000 out of 68289
Processed:  51000 out of 68289
Processed:  52000 out of 68289
Processed:  53000 out of 68289
Processed:  54000 out of 68289
Processed:  55000 out of 68289
Processed:  56000 out of 68289
Processed:  57000 out of 68289
Processed:  58000 out of 68289
Processed:  59000 out of 68289
Processed:  60000 out of 68289
Processed:  61000 out of 68289
Processed:  62000 out of 68289
Processed:  63000 out of 68289
Processed:  64000 out of 68289
Processed:  65000 out of 68289
Processed:  66000 out of 68289
Processed:  67000 out of 68289
Processed:  68000 out of 68289
STEP3: Filter paiwise clusters
[mclxIOstreamIn] no assignments yield void/empty matrix
[mcl] new tab created
___ [mclAlgorithmStart] attempting to cluster the void
[mcl] pid 58733
 ite   chaos  time hom(avg,lo,hi) m-ie m-ex i-ex fmv
  1     0.00  0.00 0.00/340282346638528859811704183484516925440.00/0.00 0.00 0.00 0.00 -2147483648
[mcl] jury pruning marks: <100,100,100>, out of 100
[mcl] jury pruning synopsis: <100.0 or really really really good> (cf -scheme, -do log)
[mcl] output is in out.mcl_list.txt.I20
[mcl] 0 clusters found
[mcl] output is in out.mcl_list.txt.I20

I'm checking what's wrong. Maybe you can give me some suggestions?

**Comment by hcli007** [comment]
I found that the problem may be caused by：
`def get_threshold_scores(cl1,cl2,conversion,thresholds,prot):`
every score in args.species.txt is 0.0
[MD.txt](https://github.com/Gabaldonlab/EvolClust/files/10963969/MD.txt)

**Comment by hcli007** [comment]
I think this is a problem of score calculation and detection mechanism, for example: 
'Pbr_12_001022	MD_04_11300	5	6	0.0	Pbr_12_01021;Pbr_12_01022;Pbr_12_01023;Pbr_12_01024;Pbr_12_01025	MD_04_11299;MD_04_11300;MD_04_11301;MD_04_11302;MD_04_11303;MD_04_11304'
This is a row of args.species.txt, Pbr_12_001022 and Pbr_12_01022 mismatch. Therefore, **the ID of all proteins must be five digits**, otherwise the script will not recognize the numerator or denominator when calculating Score.

**Comment by mmarcet** [comment]
Hi,
I'm not exactly sure what's going on, but to start with the ID of all proteins don't need to have five digits because the value is taken from the "_" symbol. There may be unexpected issues if the number of digits is not consistent across the dataset because when you transform the values to integers 001022 and 01022 will default to the same number.
About your issue, could you send me your dataset so that I can have a closer look?

**Comment by hcli007** [comment]
Here is my dataset:
mcl: Orthogroup.col2
fa: Gtri_GDDH_Ejap_Pbr.without_Scaffold.pep(too big, splite to 2)
[Orthogroups.zip](https://github.com/Gabaldonlab/EvolClust/files/10967786/Orthogroups.zip)

[Gtri_GDDH_Ejap_Pbr.without_Scaffold_1.zip](https://github.com/Gabaldonlab/EvolClust/files/10967876/Gtri_GDDH_Ejap_Pbr.without_Scaffold_1.zip)
[Gtri_GDDH_Ejap_Pbr.without_Scaffold_2.zip](https://github.com/Gabaldonlab/EvolClust/files/10967884/Gtri_GDDH_Ejap_Pbr.without_Scaffold_2.zip)

**Comment by hcli007** [comment]
Hi Marina，
Thank you for your attention to this issue.
I solved the problem after changing the ID name to five digits.
