### ISSUE TITLE
Can it be used for prokaryotic genomes?

### ISSUE THREAD

**Issue by Dx-wmc** [Gabaldonlab/EvolClust#2]
Hi, I see that the tools you developed are mainly used to search for gene clusters in eukaryotes, but bacterial genomes are relatively simpler and do not have introns. Can they be adjusted specifically for prokaryotic genomes?

**Comment by mmarcet** [comment]
Hi,
sure, you can run this on a set of prokaryotes, as you say, they are simpler than eukaryotes. You don't need to adjust anything for it to work.
